[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools >= 80.10, < 80.11",
]

[project]
name = "mlrl-util"
description = "Provides common utilities used by the mlrl-* packages."
license = "MIT"
readme = "README.md"
authors = [
    { name = "Michael Rapp", email = "michael.rapp.ml@gmail.com" },
]
keywords = [
    "utilities",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "numpy",
    "scipy",
]

[project.urls]
homepage = "https://github.com/mrapp-ke/MLRL-Boomer"
source = "https://github.com/mrapp-ke/MLRL-Boomer.git"
download = "https://github.com/mrapp-ke/MLRL-Boomer/releases"
changelog = "https://raw.githubusercontent.com/mrapp-ke/MLRL-Boomer/refs/heads/main/CHANGELOG.md"
documentation = "https://mlrl-boomer.readthedocs.io/en/latest"
issues = "https://github.com/mrapp-ke/MLRL-Boomer/issues"
