---
name: Set pull request milestone
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - feature
      - bugfix
jobs:
  set_milestone:
    name: Set pull request milestone
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Determine milestone
        uses: juliangruber/read-file-action@v1
        id: milestone
        with:
          path: build_system/res/versioning/version
      - name: Create milestone
        uses: WyriHaximus/github-action-create-milestone@v1
        with:
          title: ${{ steps.milestone.outputs.content }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Assign milestone to pull request
        uses: zoispag/action-assign-milestone@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          milestone: ${{ steps.milestone.outputs.content }}
