---
name: Retry failed workflows
on:
  workflow_run:
    types:
      - completed
    workflows:
      - Test build
      - Test building documentation
jobs:
  retry_failed_workflow:
    name: Retry failed workflows
    runs-on: ubuntu-24.04
    permissions:
      actions: write
    steps:
      - name: Rerun failed jobs
        if: >-
          ${{ github.event.workflow_run.conclusion == 'failure'
          && github.event.workflow_run.run_attempt < 3
          && github.event.workflow_run.event == 'pull_request' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          gh run rerun "${{ github.event.workflow_run.id }}" \
            --repo "${{ github.event.repository.full_name }}" \
            --failed
