---
name: Update GitHub runners
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - .github/workflows/update_github_runners.yml
      - build
      - build.bat
      - build_system/main.py
      - build_system/core/**
      - build_system/util/**
      - build_system/targets/paths.py
      - build_system/targets/dependencies/*
      - build_system/targets/dependencies/github/*
      - build_system/targets/dependencies/github/runners/*
  schedule:
    - cron: 0 3 * * 3
  workflow_dispatch:
jobs:
  update_github_runners:
    name: Update GitHub runners
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: bugfix
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: python/.version-python
      - name: Setup git
        uses: fregante/setup-git-user@v2
      - name: Generate token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.TOKEN_APP_ID }}
          private-key: ${{ secrets.TOKEN_APP_SECRET }}
      - name: Update GitHub runners
        run: |
          ./build update_github_runners
          git add .github/workflows/*.y*ml
      - name: Submit pull request
        id: pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: Update GitHub runners.
          branch: update-github-runners
          title: Update GitHub runners
          labels: bot
          assignees: mrapp-ke
          body: Update the versions of outdated GitHub-hosted runners.
      - name: Enable auto-merge
        if: ${{ steps.pull-request.outputs.pull-request-operation == 'created' }}
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh pr merge --merge --auto "${{ steps.pull-request.outputs.pull-request-number }}"
